### ISSUE TITLE
livepython fails with "SyntaxError: Unexpected token {"

### ISSUE THREAD

**Issue by ChillarAnand** [agermanidis/livepython#19]
```
livepython foo.py 
/usr/local/lib/node_modules/livepython/bin/livepython:27
const { spawn } = require("child_process");
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by abhishekgupta92** [comment]
I am facing the same issue. Any help will be appreciated.
